[package]
name = "epmon"
version = "0.2.0"
authors = ["sphereflow <johannprescher@gmx.de>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "epmon"
test = false
bench = false

[dependencies]
esp-hal = { version = "=1.0.0", features = ["esp32c6", "unstable"] }

esp-rtos = { version = "0.2.0", features = [
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32c6",
] }

esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32c6"] }

embassy-net = { version = "0.9.0", features = [
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embedded-io = "0.7.1"
embedded-io-async = "0.7.0"
esp-alloc = "0.9.0"
# for more networking protocol support see https://crates.io/crates/edge-net
embassy-executor = { version = "0.9.1", features = [] }
embassy-time = "0.5.0"
embassy-sync = "0.8.0"
esp-radio = { version = "0.17.0", features = [
  "esp-alloc",
  "esp32c6",
  "smoltcp",
  "unstable",
  "wifi",
] }
smoltcp = { version = "0.12.0", default-features = false, features = [
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }
heapless = { version = "0.9.1", default-features = false }
esp-println = { version = "0.16.0", features = ["esp32c6", "log-04"] }
log = "0.4"
rmodbus = { version = "0.12", default-features = false, features = [
  "heapless",
] }
smart-leds-trait = "0.3.2"
smart-leds = "0.4"

critical-section = "1.2.0"
static_cell = "2.1.1"


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
